web:
  build: .
  dockerfile: conf/Dockerfile.web
  ports:
    - "8000:80"
  links:
    - db
  volumes:
    - ./api:/var/www/html/api
    - ./common:/var/www/html/common
    - ./html/index.html:/var/www/html/index.php
    - ./layar:/var/www/html/layar
    - ./maintenance:/var/www/html/maintenance
    - ./map:/var/www/html/map
    - ./toolbox:/var/www/html/toolbox
    - ./toolinfo.json:/var/www/html/toolinfo.json
    - ./tools:/var/www/html/tools
db:
  build: ./conf
  dockerfile: Dockerfile.db
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: s51138__heritage_p
    MYSQL_USER: heritage
    MYSQL_PASSWORD: password
