bot:
  extends:
    file: docker-compose-base.yml
    service: bot
  links:
    - db
  environment:
    - HERITAGE_LOCAL_WRITE_PATH=docker_pages
  volumes:
    - "./conf/database_config.dev.yml:/code/erfgoedbot/database_config.yml"

db:
  extends:
    file: docker-compose-base.yml
    service: db_empty

web:
  extends:
    file: docker-compose-base.yml
    service: web
  links:
    - db
  volumes:
    - .:/var/www/
