FROM debian:jessie-slim
RUN apt-get update && \
	apt-get install -y python python-pip && \
	apt-get clean
RUN pip install --upgrade pip
ADD requirements.txt requirements.txt
RUN pip install --ignore-installed -r requirements.txt
WORKDIR /code
