FROM mysql:5.5.49

# Create all database tables
COPY ./erfgoedbot/sql/*.sql /docker-entrypoint-initdb.d/

# Remove the connect to database at the top of each SQL file
RUN sed -i 's/^connect.*$//' docker-entrypoint-initdb.d/*
