CREATE TABLE IF NOT EXISTS `admin_tree` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`level` INT NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`parent` INT
) ENGINE=INNODB DEFAULT CHARSET=utf8;
